language: node_js
node_js: 10
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn --frozen-lockfile
script:
  - yarn lint
after_success: yarn semantic-release
branches:
  only: master
